name: Build and release firmware

on: [push]

env:
  KEYBOARD: helix/rev3_4rows
  KEYMAP: m5n-keymap
  FIRMWARE: helix_rev3_4rows_m5n-keymap.hex

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone qmk/qmk_firmware
        uses: actions/checkout@v2
        with:
          repository: 'qmk/qmk_firmware'
          ref: '0.12.51'
          submodules: true

      - name: Clone this repo
        uses: actions/checkout@v2
        with:
          path: ./keyboards/${{ env.KEYBOARD }}/keymaps/${{ env.KEYMAP }}

      - name: Install dependencies
        run: ./util/qmk_install.sh

      - name: Compile
        run: ./bin/qmk compile -kb ${{ env.KEYBOARD }} -km ${{ env.KEYMAP }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./.build/${{ env.FIRMWARE }}
            ./keyboards/${{ env.KEYBOARD }}/keymaps/${{ env.KEYMAP }}/{LICENSE,README.md}

  release:
    runs-on: ubuntu-20.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.FIRMWARE }}
            LICENSE
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
