name: QMK

on: [push]

env:
  KEYBOARD: helix/rev3_4rows
  KEYMAP: m5n-keymap
  ARTIFACT: helix_rev3_4rows_m5n-keymap.hex

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone qmk/qmk_firmware
      uses: actions/checkout@v2
      with:
        repository: 'qmk/qmk_firmware'
        submodules: true
    
    - name: Clone this repo
      uses: actions/checkout@v2
      with:
        path: ./keyboards/${{ env.KEYBOARD }}/keymaps/${{ env.KEYMAP }}

    - name: Install dependencies
      run: ./util/qmk_install.sh

    - name: Compile
      run: ./bin/qmk compile -kb ${{ env.KEYBOARD }} -km ${{ env.KEYMAP }}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT }}
        path: ./.build/${{ env.ARTIFACT }}
