name: QMK

on: [push]

env:
  KEYBOARD: 'helix/rev3_4rows'
  KEYMAP: 'm5n-keymap'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone qmk/qmk_firmware
      uses: actions/checkout@v2
      with:
        repository: 'qmk/qmk_firmware'
        submodules: true
    
    - name: Clone $GITHUB_REPOSITORY
      uses: actions/checkout@v2
      with:
        path: ./keyboards/$KEYBOARD/keymaps/$KEYMAP

    - name: Install dependencies
      run: ./util/qmk_install.sh

    - name: Compile
      run: ./bin/qmk compile -kb $KEYBOARD -km $KEYMAP

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./.build/*.hex
